FROM python
RUN pip install flask
COPY ./static /home/Hoa_12.1_Portfolio/static
COPY ./templates /home/Hoa_12.1_Portfolio/templates
COPY sample_app.py /home/Hoa_12.1_Porfolio/
EXPOSE 8080
CMD python3 /home/Hoa_12.1_Portfolio/sample_app.py
FROM python
RUN pip install flask
COPY ./static /home/Hoa_12.1_Portfolio/static
COPY ./templates /home/Hoa_12.1_Portfolio/templates
COPY sample_app.py /home/Hoa_12.1_Porfolio/
EXPOSE 8080
CMD python3 /home/Hoa_12.1_Portfolio/sample_app.py
FROM python
RUN pip install flask
COPY ./static /home/Hoa_12.1_Portfolio/static
COPY ./templates /home/Hoa_12.1_Portfolio/templates
COPY sample_app.py /home/Hoa_12.1_Porfolio/
EXPOSE 8080
CMD python3 /home/Hoa_12.1_Portfolio/sample_app.py
FROM python
RUN pip install flask
COPY ./static /home/Hoa_12.1_Portfolio/static
COPY ./templates /home/Hoa_12.1_Portfolio/templates
COPY sample_app.py /home/Hoa_12.1_Porfolio/
EXPOSE 8080
CMD python3 /home/Hoa_12.1_Portfolio/sample_app.py
FROM python
RUN pip install flask
COPY ./static /home/Hoa_12.1_Portfolio/static
COPY ./templates /home/Hoa_12.1_Portfolio/templates
COPY sample_app.py /home/Hoa_12.1_Porfolio/
EXPOSE 8080
CMD python3 /home/Hoa_12.1_Portfolio/sample_app.py
FROM python
RUN pip install flask
COPY ./static /home/myapp/static
COPY ./templates /home/myapp/templates
COPY sample_app.py /home/myapp/
EXPOSE 8080
CMD python3 /home/myapp/sample_app.py
FROM python
RUN pip install flask
COPY ./static /home/myapp/static
COPY ./templates /home/myapp/templates
COPY sample_app.py /home/myapp/
EXPOSE 8080
CMD python3 /home/myapp/sample_app.py
FROM python
RUN pip install flask
COPY ./static /home/myapp/static
COPY ./templates /home/myapp/templates
COPY sample_app.py /home/myapp/
EXPOSE 8080
CMD python3 /home/myapp/sample_app.py
